rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ailuropoda_melanoleuca .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/anas_platyrhynchos .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/anolis_carolinensis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/astyanax_mexicanus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/bos_taurus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/caenorhabditis_elegans .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/callithrix_jacchus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/canis_familiaris .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/cavia_porcellus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/chlorocebus_sabaeus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/choloepus_hoffmanni .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ciona_intestinalis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ciona_savignyi .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/danio_rerio .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/dasypus_novemcinctus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/dipodomys_ordii .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/drosophila_melanogaster .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/echinops_telfairi .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/equus_caballus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/erinaceus_europaeus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/felis_catus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ficedula_albicollis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/gadus_morhua .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/gallus_gallus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/gasterosteus_aculeatus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/gorilla_gorilla .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/homo_sapiens .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ictidomys_tridecemlineatus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/latimeria_chalumnae .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/lepisosteus_oculatus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/loxodonta_africana .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/macaca_mulatta .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/macropus_eugenii .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/meleagris_gallopavo .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/microcebus_murinus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/monodelphis_domestica .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/mus_musculus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/mustela_putorius_furo .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/myotis_lucifugus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/nomascus_leucogenys .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ochotona_princeps .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/oreochromis_niloticus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ornithorhynchus_anatinus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/oryctolagus_cuniculus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/oryzias_latipes .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/otolemur_garnettii .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/ovis_aries .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/pan_troglodytes .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/papio_anubis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/pelodiscus_sinensis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/petromyzon_marinus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/poecilia_formosa .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/pongo_abelii .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/procavia_capensis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/pteropus_vampyrus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/rattus_norvegicus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/saccharomyces_cerevisiae .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/sarcophilus_harrisii .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/sorex_araneus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/sus_scrofa .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/taeniopygia_guttata .
#rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/tarsius_syrichta .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/tetraodon_nigroviridis .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/tursiops_truncatus .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/vicugna_pacos .
rsync -av rsync://ftp.ensembl.org/ensembl/pub/current_genbank/xenopus_tropicalis .
